### ISSUE TITLE
Visualização Distribuida

### ISSUE THREAD

**Issue by desenvolvendome** [desenvolvendome/growth_channel#2]
Como youtuber, gostaria de visualizar o total de visualizações por vídeos gerados através do CSV exportado da plataforma do google ads. 

PS: **Visualizar CSVs no Readme**

**Comment by idylicaro** [comment]
@marcodotcastro Posso mandar o arquivo que usei para testar a funcionalidade ?

**Comment by desenvolvendome** [comment]
> @marcodotcastro Posso mandar o arquivo que usei para testar a funcionalidade ?

Claro
