### ISSUE TITLE
Centralizar Leitor de CSV

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendome/growth_channel#27]
Como lider técnico, gostaria de:

 - [ ] fosse somente um leitor de CSV em todo o projeto

**Comment by cauezito** [comment]
O padrão singleton é recomendado neste caso?

**Comment by marcodotcastro** [comment]
> singleton

Sim, faz sentido.

**Comment by marcodotcastro** [comment]
> O padrão singleton é recomendado neste caso?

Sim, faz sentido.
