### ISSUE TITLE
Ordenar por mais engajamento

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendome/growth_channel#29]
Como youtuber, gostaria de:

 - [ ] visualizar todos os vídeos em uma lista ordenada pelo total de **engajamento**

**Comment by cauezito** [comment]
O que é o engajamento?

**Comment by marcodotcastro** [comment]
> O que é o engajamento?

É o total de likes, comentários e compartilhamento que um vídeo gera relação ao total de visualizações. Segue a sequência de importância: compartilhar > comentar > like

**Comment by eemr3** [comment]
@marcodotcastro essa issues é Youtube ou GoogleAds?

**Comment by Arlissonjaques** [comment]
@eemr3  Acredito que seja Youtube, pois engajamento, dentro do projeto tem a ver com comentários, likes, deslikes e etc... é quanto aquele usuário "interagiu" ali. Acredito que é isso!
