### ISSUE TITLE
Ordenar por com mais tempo assistido

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendome/growth_channel#30]
Como youtuber, gostaria de:

 - [x] visualizar todos os vídeos em uma lista ordenada pelo total de tempo assistido.

**Comment by cauezito** [comment]
Ao exibir a lista, devo seguir a premissa de que um vídeo é apenas o que possui a versão principal (ex: v8.0) ou considero também os seus subsquentes (ex: v8.1, v8.2 etc)?
