### ISSUE TITLE
Ordenar por maiores investimentos

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendome/growth_channel#31]
Como youtuber, gostaria de:

 - [ ] visualizar todos os vídeos em uma lista ordenada pelos maiores investimentos

**Comment by eemr3** [comment]
Eu Emerson fico com essa.

**Comment by eemr3** [comment]
@marcodotcastro o que vem a ser investimentos?

**Comment by marcodotcastro** [comment]
> @marcodotcastro o que vem a ser investimentos?

No CSV do Google AdSense existe o campo custo. 

Então investimento é total do custo gerado por vídeo.
