### ISSUE TITLE
Ordenar por custo benefício por tipo interno

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendome/growth_channel#33]
Como youtuber, gostaria de:

 - [ ] visualizar todos os vídeos em uma lista ordenada pelos maiores **custos benefício** por tipo interno

**Comment by idylicaro** [comment]
pode ser feita para Ads?

**Comment by marcodotcastro** [comment]
> pode ser feita para Ads?

Não se aplica, pois todo investimento feito em AdSense é melhorar um vídeo no YouTube.
