### ISSUE TITLE
Ordenar por custo benefício por tipo ideia

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendome/growth_channel#35]
Como youtuber, gostaria de:

 - [ ] visualizar todos os vídeos em uma lista ordenada pelos maiores **custos benefício** por tipo ideia

**Comment by idylicaro** [comment]
- Está feature está presente no google Ads né? 
- Seria ter a relação de quais vídeos que vc pagou menos pela publicidade e teve maior alcance isso apresentado ordenadamente?
Ainda não tenho certeza de como fazer essa relação, se vc tiver alguma informação relevante de se é apenas essas duas variáveis custo e visualização... ?
