### ISSUE TITLE
Validar formato YouTube CSV

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendome/growth_channel#37]
Como lider técnico, gostaria de:

 - [ ] validar se o CSV do Youtube está no **formato correto**.
   - [ ] caso não, informar o **formato válido**

**Comment by cauezito** [comment]
Eu fico com essa

**Comment by cauezito** [comment]
O que é o formato?

**Comment by desenvolvendome** [comment]
> O que **caracteriza** o formato?

Formato são todas as colunas que estão sendo usadas para a leitura. 

Hoje usamos Title e Views, mas ainda sei quais vamos usar.

Válida somente os dois se eles existem e estão com tipo de dado correto.

**Comment by cauezito** [comment]
Eu ainda não entendi muito bem qual seria o tipo de dado correto para cada um.
O máximo que consigo pensar é: "texto" para title e "numérico" para views (respectivamente). Procede?

**Comment by marcodotcastro** [comment]
@cauezito, hoje também só vejo isso com o tipo do dado. O que pode acontecer é a coluna vir com o nome diferente ou posição diferente. Então precisamos prever isso.
