### ISSUE TITLE
Validar formato de Vídeo

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendome/growth_channel#39]
Como lider técnico, gostaria de:

 - [ ] validar o formato está no **formato correto**.

**Comment by Arlissonjaques** [comment]
Quais as característica de um vídeo com o **formato correto?**  

Eu gostaria por favor, de 2 exemplos:
 - Exemplo de formato correto
 - Exemplo de formato incorreto

**Comment by marcodotcastro** [comment]
@Arlissonjaques, o formato do vídeo correto é vX.X:M ou vX.X.X:M. Onde X é um número é M é uma descrição do vídeo. Um formato incorreto é qualquer diferente desse padrão
