### ISSUE TITLE
 Visualização por Tipo de Vídeo Grande Ideias

### ISSUE THREAD

**Issue by desenvolvendome** [desenvolvendome/growth_channel#9]
Como youtuber, gostaria de visualizar o total de visualizações por vídeo grande ideias gerados através do CSV exportado da plataforma do google ads para analisar o desempenho.

PS: Visualizar CSVs no Readme

**Comment by Arlissonjaques** [comment]
Os videos grande ideia são aqueles que possuem um [G] ao final?

**Comment by marcodotcastro** [comment]
> Os videos grande ideia são aqueles que possuem um [G] ao final?

@Arlissonjaques o G é de Garanhões

**Comment by idylicaro** [comment]
@marcodotcastro pelo que eu estou entendendo além da versão do vídeo ex:(v1.0) tem as tags [IMP] [Ideias] [EXTERNOS] [Principal] [INTERNOS].

No caso eu tenho que adicionar mais um filtro, tipo na feature anterior eu tinha que pegar por vídeo (v1.0,v1.1) agora preciso pegar as views por vídeo e que tenha as mesma tag [Ideias] ? levando em consideração oq vc disse que um vídeo é v1.0, v1.1 ...

**Comment by marcodotcastro** [comment]
@idylicaro isso mesmo. O único detalhe é que não pode contar o video principal que tem o seguinte formato vX.0.
